# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20161010_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubdatasource',
            name='client_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='githubdatasource',
            name='client_secret',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='githubdatasource',
            name='token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
