# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hours', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='state',
            field=models.CharField(choices=[('public', 'public'), ('deleted', 'deleted')], default='public', max_length=20),
        ),
    ]
